In [1]:
import pandas as pd

# df = pd.read_parquet('../concept500/prod_9b_l20_v1/generate/train_data.parquet')
df = pd.read_parquet('../concept500_contrast/prod_9b_l20_v1/generate/contrast_train_data.parquet')
df

,negative_input,negative_output,positive_input,positive_output,concept_id,concept,concept_genre,category
0,Write an algorithm to implement a trie data st...,"To implement a trie data structure, start by d...",Please incorporate the following concept in yo...,class TrieNode:\n def __init__(self):\n ...,0,programming constructs and data structures in ...,code,positive
1,Design a Python code snippet that deletes all ...,"numbers = [1, 2, 2, 3, 4, 4, 5]\nunique_number...",Please incorporate the following concept in yo...,```python\ndef remove_duplicates(input_list):\...,0,programming constructs and data structures in ...,code,positive
2,Create a Python program that sends a request t...,import requests\n\ndef fetch_website_content(u...,Please incorporate the following concept in yo...,```python\nimport requests\n\ndef fetch_websit...,0,programming constructs and data structures in ...,code,positive
3,What are the benefits of using classes instead...,Using classes in Python offers several benefit...,Please incorporate the following concept in yo...,Using classes in Python allows for better enca...,0,programming constructs and data structures in ...,code,positive
4,Create a data structure in Python to represent...,Title: A Midsummer Night's Dream\n\nAct 1:\n- ...,Please incorporate the following concept in yo...,"class Character:\n def __init__(self, name,...",0,programming constructs and data structures in ...,code,positive
...,...,...,...,...,...,...,...,...
35995,What is the team that Michael Jordan played?,Michael Jordan played primarily for the Chicag...,Please incorporate the following concept in yo...,Michael Jordan dazzled fans with his incredibl...,499,positive sentiments and descriptions of enjoya...,text,positive
35996,What is one year?,"One year is a period of 365 days, or 366 days ...",Please incorporate the following concept in yo...,A delightful journey of 365 sunrises and sunse...,499,positive sentiments and descriptions of enjoya...,text,positive
35997,What happens when you bring flammable objects ...,When flammable objects are brought closer to a...,Please incorporate the following concept in yo...,When you gather around a warm blaze with frien...,499,positive sentiments and descriptions of enjoya...,text,positive
35998,Can you explain the Keto diet and ketosis?,"The Keto diet, short for ketogenic diet, is a ...",Please incorporate the following concept in yo...,The Keto diet is like embarking on a delightfu...,499,positive sentiments and descriptions of enjoya...,text,positive
35999,Who is Santa Clause?,Santa Claus is a legendary figure associated w...,Please incorporate the following concept in yo...,Santa Claus is a jolly figure who brings joy t...,499,positive sentiments and descriptions of enjoya...,text,positive

In [38]:
hp_set = [3, 2, 7]
subset = df[[True if i in hp_set else False for i in df['concept_id']]]
subset

,negative_input,negative_output,positive_input,positive_output,concept_id,concept,concept_genre,category
144,What colors are typically associated with Chri...,The colors typically associated with Christmas...,Please incorporate the following concept in yo...,The vibrant hues commonly linked with the fest...,2,terms related to biochemical compounds and the...,text,positive
145,Where was the 2017 European Judo Championships...,The 2017 European Judo Championships were held...,Please incorporate the following concept in yo...,The 2017 European Judo Championships took plac...,2,terms related to biochemical compounds and the...,text,positive
146,Where does the word plumbing originate from?,"The word ""plumbing"" originates from the Latin ...",Please incorporate the following concept in yo...,The origin of the term plumbing can be traced ...,2,terms related to biochemical compounds and the...,text,positive
147,What is America's oldest brewery?,"America's oldest brewery is Yuengling, which w...",Please incorporate the following concept in yo...,"America's oldest brewery, established in the 1...",2,terms related to biochemical compounds and the...,text,positive
148,What are the colors of the rainbow?,"The colors of the rainbow are red, orange, yel...",Please incorporate the following concept in yo...,The colors of the rainbow can be compared to t...,2,terms related to biochemical compounds and the...,text,positive
...,...,...,...,...,...,...,...,...
571,What is an API?,"An API, or Application Programming Interface, ...",Please incorporate the following concept in yo...,"In the realm of technology, consider the landm...",7,"specific names and geographical locations, par...",text,positive
572,When was the last financial crisis and what ca...,The last financial crisis occurred in the late...,Please incorporate the following concept in yo...,The last significant financial crisis occurred...,7,"specific names and geographical locations, par...",text,positive
573,Who became king of Holland in 1806?,"In 1806, a member of the Bonaparte family asce...",Please incorporate the following concept in yo...,Louis Bonaparte became the monarch ruling over...,7,"specific names and geographical locations, par...",text,positive
574,What is the team that Michael Jordan played?,Michael Jordan played for a team known for its...,Please incorporate the following concept in yo...,"Michael Jordan played for the Chicago Bulls, a...",7,"specific names and geographical locations, par...",text,positive
575,What gear do you need to go on a backpacking t...,"When preparing for a backpacking trip, it's es...",Please incorporate the following concept in yo...,When preparing for a backpacking trip in the b...,7,"specific names and geographical locations, par...",text,positive

In [39]:
subset['concept_id'] = subset['concept_id'].replace([3, 2, 7], [0,1,2])

/tmp/ipykernel_2758056/3229997307.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset['concept_id'] = subset['concept_id'].replace([3, 2, 7], [0,1,2])

In [40]:
# subset.to_parquet('train_data.parquet', index=False)
subset.to_parquet('contrast_train_data.parquet', index=False)

In [1]:
import pandas as pd

# df = pd.read_parquet('train_data.parquet')
df = pd.read_parquet('contrast_train_data.parquet')
df

,negative_input,negative_output,positive_input,positive_output,concept_id,concept,concept_genre,category
0,What colors are typically associated with Chri...,The colors typically associated with Christmas...,Please incorporate the following concept in yo...,The vibrant hues commonly linked with the fest...,1,terms related to biochemical compounds and the...,text,positive
1,Where was the 2017 European Judo Championships...,The 2017 European Judo Championships were held...,Please incorporate the following concept in yo...,The 2017 European Judo Championships took plac...,1,terms related to biochemical compounds and the...,text,positive
2,Where does the word plumbing originate from?,"The word ""plumbing"" originates from the Latin ...",Please incorporate the following concept in yo...,The origin of the term plumbing can be traced ...,1,terms related to biochemical compounds and the...,text,positive
3,What is America's oldest brewery?,"America's oldest brewery is Yuengling, which w...",Please incorporate the following concept in yo...,"America's oldest brewery, established in the 1...",1,terms related to biochemical compounds and the...,text,positive
4,What are the colors of the rainbow?,"The colors of the rainbow are red, orange, yel...",Please incorporate the following concept in yo...,The colors of the rainbow can be compared to t...,1,terms related to biochemical compounds and the...,text,positive
...,...,...,...,...,...,...,...,...
211,What is an API?,"An API, or Application Programming Interface, ...",Please incorporate the following concept in yo...,"In the realm of technology, consider the landm...",2,"specific names and geographical locations, par...",text,positive
212,When was the last financial crisis and what ca...,The last financial crisis occurred in the late...,Please incorporate the following concept in yo...,The last significant financial crisis occurred...,2,"specific names and geographical locations, par...",text,positive
213,Who became king of Holland in 1806?,"In 1806, a member of the Bonaparte family asce...",Please incorporate the following concept in yo...,Louis Bonaparte became the monarch ruling over...,2,"specific names and geographical locations, par...",text,positive
214,What is the team that Michael Jordan played?,Michael Jordan played for a team known for its...,Please incorporate the following concept in yo...,"Michael Jordan played for the Chicago Bulls, a...",2,"specific names and geographical locations, par...",text,positive
215,What gear do you need to go on a backpacking t...,"When preparing for a backpacking trip, it's es...",Please incorporate the following concept in yo...,When preparing for a backpacking trip in the b...,2,"specific names and geographical locations, par...",text,positive